Mobile  & Desktop version
chiztechnology/Africa-Summit pull request #1
Opened 2022-11-23 17:44 UTC by chiztechnology

Hello these are some interesting featured developped in my capstone 1 project.
Please have a look on the code and on functionnalities and let me know if there's something that require changes or if I can merge it to my main branch.

Faithfully yours 🎊

2022-11-23 22:13 UTC, OLIPLICHE requested changes
Hi @chiztechnology, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Linter is green (the last commit has a green check mark (✅)) 👏
- README file is descriptive 👏
- Commit messages are meaningful 👏 👏
- GitHub flow is correctly used (Pull Request is made from the feature branch into the main branch) 👏

## Required Changes ♻️
- Please follow the original DESIGN as indicated in the requirement of this Project.
- [Here is the link to the Design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 22:13 UTC, OLIPLICHE commented on README.md
> +
- Make sure to record a video presenting the features of the project. The maximum length of the video needs to be 5 minutes. Also, highlight a piece of the code that you find interesting or are proud of making.

2022-11-23 22:13 UTC, OLIPLICHE commented on README.md
> +## 🙏 Acknowledgments <a name="acknowledgements"></a>
- Make sure the README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-11-23 22:13 UTC, OLIPLICHE commented on index.html
> +        </nav>
- **Mobile Size**:
- Make sure It contains a hamburger menu on the left side.
- Its background is transparent or the same color/pattern as the top section background.
- See an Example from the original design:
- 
- 
![Capture](https://user-images.githubusercontent.com/63972670/203643487-41aff790-cc7d-4073-822c-585a339876f3.PNG)
-
- See your design:
- 
![Capture](https://user-images.githubusercontent.com/63972670/203644192-d173d477-f385-476b-8b8f-2b775796089d.PNG)

2022-11-23 22:13 UTC, OLIPLICHE commented on index.html
> +        </nav>
# **Desktop Size**: Make sure that
- It is divided in a top dark bar and a bottom white bar.
- The top short bar section with social media links, log out, and language links aligned to the right.
- The taller bottom bar with a logo and a list of page links.
- 
![Capture](https://user-images.githubusercontent.com/63972670/203645880-52efbae2-9286-4440-86ce-da53fd3b6739.PNG)
- 
- **Your design**
![Capture](https://user-images.githubusercontent.com/63972670/203646172-e1ce324a-60a5-4885-b00b-518eb1900f06.PNG)
# NB:
- **About Page: It has a dark background**.
- 
![Capture1](https://user-images.githubusercontent.com/63972670/203648936-d5120a23-c4a9-413e-a390-a61616942782.PNG)

- **Home Page: It has a white background.**
- 
![Capture](https://user-images.githubusercontent.com/63972670/203648900-51f6f086-5fb7-4a67-b508-677c91a9fa01.PNG)

2022-11-23 22:13 UTC, OLIPLICHE commented on index.html
> +    <footer>
- **Footer: Mobile Size**
- Please work on the height of the footer.
- **See your design**
- 
![Capture](https://user-images.githubusercontent.com/63972670/203647194-a68a7d34-9ba2-48b2-992f-1098d7a12ce4.PNG)
- **Original Design**
- 
![Capture](https://user-images.githubusercontent.com/63972670/203647362-76bcebc9-b078-429b-9329-132cd1fe8c5d.PNG)

2022-11-23 22:13 UTC, OLIPLICHE commented on index.html
> +            </div>
- **Please provide six (6) individual articles, Not four (4)**
- 
![Capture](https://user-images.githubusercontent.com/63972670/203650077-56b236cc-6800-40f5-9b64-ea009865720b.PNG)
- **Your Design**:
- 
![Capture](https://user-images.githubusercontent.com/63972670/203650240-d13747a5-a283-46f8-87f1-146c3f8480cd.PNG)

2022-11-23 22:13 UTC, OLIPLICHE commented on about.html
> +    <body>
# Mobile Size
- The middle section article list is organized in a vertical column.
- The middle section individual articles have their elements organized in an horizontal row, with the image at the left, title in the center, and description at the right.
- The bottom section articles are organized in a vertical column.
- **Your Design**:
- 
![Capture](https://user-images.githubusercontent.com/63972670/203650848-0189e8e8-a520-4175-a52f-9c8c596b880b.PNG)
- **NB: Please open this link to refer to the[ Original Design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)**

2022-11-23 22:13 UTC, OLIPLICHE commented on about.html
> +        <main>
# About Page
- It contains a top section with a centered column that includes a page title, a text block with the page description, and a line with a contact information or any other prompt under it.
- 
![Capture1](https://user-images.githubusercontent.com/63972670/203651985-bb81be36-46e3-4026-a7be-42a93188c0ba.PNG)
- **Please follow the original design**
- 
![Capture](https://user-images.githubusercontent.com/63972670/203652191-d7e2f435-eb85-41e7-81cd-50d5f1c618cc.PNG)

2022-11-23 22:13 UTC, OLIPLICHE commented on about.html
> +                </div>
- NB: Please, the Section tag `<section>` defines the section of documents such as chapters, headers, footers or any other sections. Kindly make use of it in About and index HTML.
- Use this link to learn more about[ Semantic HTML ](https://www.w3schools.com/html/html5_semantic_elements.asp)

2022-11-23 22:13 UTC, OLIPLICHE commented on index.html
> +                <h1 class="welcome-date-txt">2015.10.15(THU) ~ 16(FRI)</h1>
- **Please, Here's how Hn tags should be used:** For an article or webpage, remember that the H1 title is the most important section. H2 and H3 are used to organize sub-sections, while H4, H5, and H6 are intended to provide additional information, with more details.
- Kindly Fix the use of `h1` in both inde.html and About.Html

2022-11-24 21:37 UTC, nedjwab approved these changes
# 🟢 Project Approved! 🏆

## Hi @chiztechnology    👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-24 21:38 UTC, merged